### ISSUE TITLE
cloud functions

### ISSUE THREAD

**Issue by jasonboateng** [amarjeet987/Simple-Blood-Donation-App#2]
pls can you help me out with a sample code or anything to start with pls

**Comment by jasonboateng** [comment]
hello pls the cloud function am new to firestore pls help me out

**Comment by amarjeet987** [comment]
Getting started with cloud functions : 
https://firebase.google.com/docs/functions/get-started

Using cloud functions with firestore : 
https://firebase.google.com/docs/firestore/extend-with-functions

Also, you can refer to another project of mine, I have used and uploaded the cloud functions for that as well : 
https://github.com/amarjeet987/EventManagementSystem

Also, you can check this blog post, it's beautifully explained here, how to set up push notifications using Cloud functions and Firebase Cloud Messaging : 
https://codingwithmitch.com/blog/android-firebase-cloud-messages-cloud-function/

**Comment by amarjeet987** [comment]
Also, you can check

**Comment by jasonboateng** [comment]
thanks so much

**Comment by jasonboateng** [comment]
just a bit confused  if u help me write would be glad thank you
